/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class FrmAverCalculator extends javax.swing.JFrame {

    /**
     * Creates new form FrmAverCalculator
     */
    public FrmAverCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        lblLnst1 = new javax.swing.JLabel();
        lblCourseMark1 = new javax.swing.JLabel();
        lblCourseMark2 = new javax.swing.JLabel();
        lblCourseMark3 = new javax.swing.JLabel();
        lblCourseMark4 = new javax.swing.JLabel();
        lblAverageValue = new javax.swing.JLabel();
        btnCalculateAver = new javax.swing.JButton();
        txtMark4 = new javax.swing.JTextField();
        txtMark1 = new javax.swing.JTextField();
        txtMark3 = new javax.swing.JTextField();
        txtMark2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHeader.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(153, 0, 51));
        lblHeader.setText("Course Mark Average Calculator");

        lblLnst1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblLnst1.setText("Enter in your four course marks and click Calculate Average.");

        lblCourseMark1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCourseMark1.setText("Course Mark 1:");

        lblCourseMark2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCourseMark2.setText("Course Mark 2:");

        lblCourseMark3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCourseMark3.setText("Course Mark 3:");

        lblCourseMark4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCourseMark4.setText("Course Mark 4:");

        lblAverageValue.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblAverageValue.setText("Average");

        btnCalculateAver.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCalculateAver.setText("Calculate Average");
        btnCalculateAver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateAverActionPerformed(evt);
            }
        });

        txtMark4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtMark1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtMark3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtMark3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMark3ActionPerformed(evt);
            }
        });

        txtMark2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtMark2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMark2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCourseMark2)
                    .addComponent(lblCourseMark1)
                    .addComponent(lblCourseMark3)
                    .addComponent(lblCourseMark4))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMark4)
                    .addComponent(txtMark3)
                    .addComponent(txtMark2)
                    .addComponent(txtMark1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(lblHeader)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCalculateAver)
                        .addGap(129, 129, 129))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblAverageValue)
                        .addGap(171, 171, 171))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblLnst1)
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(lblLnst1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCourseMark2)
                            .addComponent(txtMark2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCourseMark1)
                        .addComponent(txtMark1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseMark3)
                    .addComponent(txtMark3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseMark4)
                    .addComponent(txtMark4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnCalculateAver)
                .addGap(18, 18, 18)
                .addComponent(lblAverageValue)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateAverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateAverActionPerformed
        // TODO add your handling code here:
        //variables
        int mark1;
        int mark2;
        int mark3;
        int mark4;
        double roundAverage;
        double average;
        
        //get user input
         mark1 = Integer.parseInt(txtMark1.getText());
         mark2 = Integer.parseInt(txtMark2.getText());
         mark3 = Integer.parseInt(txtMark3.getText());
         mark4 = Integer.parseInt(txtMark4.getText());
         
         //Calculaion 
         average =(double) ((mark1 + mark2 + mark3 + mark4)/4.0);
         roundAverage = Math.round(average*10)/10.0;
         lblAverageValue.setText(String.valueOf(roundAverage));
    }//GEN-LAST:event_btnCalculateAverActionPerformed

    private void txtMark3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMark3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMark3ActionPerformed

    private void txtMark2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMark2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMark2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAverCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAverCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAverCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAverCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAverCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculateAver;
    private javax.swing.JLabel lblAverageValue;
    private javax.swing.JLabel lblCourseMark1;
    private javax.swing.JLabel lblCourseMark2;
    private javax.swing.JLabel lblCourseMark3;
    private javax.swing.JLabel lblCourseMark4;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblLnst1;
    private javax.swing.JTextField txtMark1;
    private javax.swing.JTextField txtMark2;
    private javax.swing.JTextField txtMark3;
    private javax.swing.JTextField txtMark4;
    // End of variables declaration//GEN-END:variables
}
